apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: tejumasha/react-app1:latest  
          ports:
            - containerPort: 3000
          
      imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: dev  
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001  
  selector:
    app: react-app
